force-app/main/default/objects/Grid_Column__mdt/Grid_Column__mdt.object-meta.xml
<CustomObject>
    <label>Grid Column</label>
    <pluralLabel>Grid Columns</pluralLabel>
</CustomObject>

force-app/main/default/objects/Grid_Column__mdt/fields/Grid_Config__c.field-meta.xml
<CustomField>
    <fullName>Grid_Config__c</fullName>
    <label>Grid Config</label>
    <referenceTo>Grid_Config__mdt</referenceTo>
    <relationshipLabel>Grid Columns</relationshipLabel>
    <relationshipName>Grid_Columns</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/Grid_Column__mdt/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>action</fullName>
            </value>
            <value>
                <fullName>boolean</fullName>
            </value>
            <value>
                <fullName>button</fullName>
            </value>
            <value>
                <fullName>button-icon</fullName>
            </value>
            <value>
                <fullName>currency</fullName>
            </value>
            <value>
                <fullName>date</fullName>
            </value>
            <value>
                <fullName>date-local</fullName>
            </value>
            <value>
                <fullName>location</fullName>
            </value>
            <value>
                <fullName>number</fullName>
            </value>
            <value>
                <fullName>percent</fullName>
            </value>
            <value>
                <fullName>phone</fullName>
            </value>
            <value>
                <fullName>text</fullName>
            </value>
            <value>
                <fullName>url</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Grid_Config__mdt/Grid_Config__mdt.object-meta.xml
<CustomObject>
    <label>Grid Config</label>
    <pluralLabel>Grid Configs</pluralLabel>
</CustomObject>

force-app/main/default/objects/Grid_Config__mdt/fields/default_sort_direction__c.field-meta.xml
<CustomField>
    <fullName>default_sort_direction__c</fullName>
    <label>default-sort-direction</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Grid_Config__mdt/fields/enable_infinite_loading__c.field-meta.xml
<CustomField>
    <fullName>enable_infinite_loading__c</fullName>
    <defaultValue>false</defaultValue>
    <label>enable-infinite-loading</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Grid_Config__mdt/fields/hide_checkbox_column__c.field-meta.xml
<CustomField>
    <fullName>hide_checkbox_column__c</fullName>
    <defaultValue>false</defaultValue>
    <label>hide-checkbox-column</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Grid_Config__mdt/fields/hide_table_header__c.field-meta.xml
<CustomField>
    <fullName>hide_table_header__c</fullName>
    <defaultValue>false</defaultValue>
    <label>hide-table-header</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Grid_Config__mdt/fields/Key_Field__c.field-meta.xml
<CustomField>
    <fullName>Key_Field__c</fullName>
    <defaultValue>&quot;id&quot;</defaultValue>
    <label>Key Field</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Grid_Config__mdt/fields/load_more_offset__c.field-meta.xml
<CustomField>
    <fullName>load_more_offset__c</fullName>
    <defaultValue>20</defaultValue>
    <label>load-more-offset</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Grid_Config__mdt/fields/max_column_width__c.field-meta.xml
<CustomField>
    <fullName>max_column_width__c</fullName>
    <defaultValue>&#39;1000px&#39;</defaultValue>
    <label>max-column-width</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Grid_Config__mdt/fields/max_row_selection__c.field-meta.xml
<CustomField>
    <fullName>max_row_selection__c</fullName>
    <label>max-row-selection</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Grid_Config__mdt/fields/min_column_width__c.field-meta.xml
<CustomField>
    <fullName>min_column_width__c</fullName>
    <defaultValue>&#39;50px&#39;</defaultValue>
    <label>min-column-width</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Grid_Config__mdt/fields/resize_column_disabled__c.field-meta.xml
<CustomField>
    <fullName>resize_column_disabled__c</fullName>
    <defaultValue>false</defaultValue>
    <label>resize-column-disabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Grid_Config__mdt/fields/resize_step__c.field-meta.xml
<CustomField>
    <fullName>resize_step__c</fullName>
    <defaultValue>&#39;10px&#39;</defaultValue>
    <label>resize-step</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Grid_Config__mdt/fields/row_number_offset__c.field-meta.xml
<CustomField>
    <fullName>row_number_offset__c</fullName>
    <label>row-number-offset</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Grid_Config__mdt/fields/show_row_number_column__c.field-meta.xml
<CustomField>
    <fullName>show_row_number_column__c</fullName>
    <defaultValue>false</defaultValue>
    <label>show-row-number-column</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Grid_Config__mdt/fields/sorted_by__c.field-meta.xml
<CustomField>
    <fullName>sorted_by__c</fullName>
    <label>sorted-by</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Grid_Config__mdt/fields/sorted_direction__c.field-meta.xml
<CustomField>
    <fullName>sorted_direction__c</fullName>
    <label>sorted-direction</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>asc</fullName>
                <default>true</default>
                <label>asc</label>
            </value>
            <value>
                <fullName>desc</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Grid_Config__mdt/fields/suppress_bottom_bar__c.field-meta.xml
<CustomField>
    <fullName>suppress_bottom_bar__c</fullName>
    <defaultValue>false</defaultValue>
    <label>suppress-bottom-bar</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Grid_Config__mdt/fields/wrap_text_max_lines__c.field-meta.xml
<CustomField>
    <fullName>wrap_text_max_lines__c</fullName>
    <label>wrap-text-max-lines</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/GridController.cls
public with sharing class GridController {
  @AuraEnabled
  public static GridConfig getGridConfig(
    String gridConfigName,
    List<String> criteriaParams
  ) {
    System.debug('called getGridConfig');
    GridConfig config = new GridConfig(gridConfigName, criteriaParams);
    System.debug(config);
    return config;
  }

  @AuraEnabled
  public static Map<String, GridConfig> getGridConfigs(
    List<String> gridConfigNames
  ) {
    Map<String, GridConfig> configs = new Map<String, GridConfig>();
    List<Grid_Config__mdt> gridConfigs = [
      SELECT
        Id,
        DeveloperName,
        MasterLabel,
        Label,
        QualifiedApiName,
        Query__c,
        Key_Field__c,
        default_sort_direction__c,
        enable_infinite_loading__c,
        hide_checkbox_column__c,
        hide_table_header__c,
        load_more_offset__c,
        max_column_width__c,
        max_row_selection__c,
        min_column_width__c,
        resize_column_disabled__c,
        resize_step__c,
        row_number_offset__c,
        show_row_number_column__c,
        sorted_by__c,
        sorted_direction__c,
        suppress_bottom_bar__c,
        wrap_text_max_lines__c,
        (
          SELECT
            Id,
            Label,
            Grid_Config__c,
            Field_Name__c,
            Type__c,
            Sort_Order__c
          FROM Grid_Columns__r
        )
      FROM Grid_Config__mdt
      WHERE DeveloperName IN :gridConfigNames
    ];
    for (Grid_Config__mdt gridConfig : gridConfigs) {
      configs.put(gridConfig.DeveloperName, new GridConfig(gridConfig));
    }
    return configs;
  }
}