force-app/main/default/objects/Grid_Column__mdt/Grid_Column__mdt.object-meta.xml
<CustomObject>
    <label>Grid Column</label>
    <pluralLabel>Grid Columns</pluralLabel>
</CustomObject>

force-app/main/default/objects/Grid_Column__mdt/fields/Grid_Config__c.field-meta.xml
<CustomField>
    <fullName>Grid_Config__c</fullName>
    <label>Grid Config</label>
    <referenceTo>Grid_Config__mdt</referenceTo>
    <relationshipLabel>Grid Columns</relationshipLabel>
    <relationshipName>Grid_Columns</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/Grid_Column__mdt/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>action</fullName>
            </value>
            <value>
                <fullName>boolean</fullName>
            </value>
            <value>
                <fullName>button</fullName>
            </value>
            <value>
                <fullName>button-icon</fullName>
            </value>
            <value>
                <fullName>currency</fullName>
            </value>
            <value>
                <fullName>date</fullName>
            </value>
            <value>
                <fullName>date-local</fullName>
            </value>
            <value>
                <fullName>location</fullName>
            </value>
            <value>
                <fullName>number</fullName>
            </value>
            <value>
                <fullName>percent</fullName>
            </value>
            <value>
                <fullName>phone</fullName>
            </value>
            <value>
                <fullName>text</fullName>
            </value>
            <value>
                <fullName>url</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Grid_Config__mdt/Grid_Config__mdt.object-meta.xml
<CustomObject>
    <label>Grid Config</label>
    <pluralLabel>Grid Configs</pluralLabel>
</CustomObject>

force-app/main/default/objects/Grid_Config__mdt/fields/default_sort_direction__c.field-meta.xml
<CustomField>
    <fullName>default_sort_direction__c</fullName>
    <label>default-sort-direction</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Grid_Config__mdt/fields/enable_infinite_loading__c.field-meta.xml
<CustomField>
    <fullName>enable_infinite_loading__c</fullName>
    <defaultValue>false</defaultValue>
    <label>enable-infinite-loading</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Grid_Config__mdt/fields/hide_checkbox_column__c.field-meta.xml
<CustomField>
    <fullName>hide_checkbox_column__c</fullName>
    <defaultValue>false</defaultValue>
    <label>hide-checkbox-column</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Grid_Config__mdt/fields/hide_table_header__c.field-meta.xml
<CustomField>
    <fullName>hide_table_header__c</fullName>
    <defaultValue>false</defaultValue>
    <label>hide-table-header</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Grid_Config__mdt/fields/Key_Field__c.field-meta.xml
<CustomField>
    <fullName>Key_Field__c</fullName>
    <defaultValue>&quot;id&quot;</defaultValue>
    <label>Key Field</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Grid_Config__mdt/fields/load_more_offset__c.field-meta.xml
<CustomField>
    <fullName>load_more_offset__c</fullName>
    <defaultValue>20</defaultValue>
    <label>load-more-offset</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Grid_Config__mdt/fields/max_column_width__c.field-meta.xml
<CustomField>
    <fullName>max_column_width__c</fullName>
    <defaultValue>&#39;1000px&#39;</defaultValue>
    <label>max-column-width</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Grid_Config__mdt/fields/max_row_selection__c.field-meta.xml
<CustomField>
    <fullName>max_row_selection__c</fullName>
    <label>max-row-selection</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Grid_Config__mdt/fields/min_column_width__c.field-meta.xml
<CustomField>
    <fullName>min_column_width__c</fullName>
    <defaultValue>&#39;50px&#39;</defaultValue>
    <label>min-column-width</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Grid_Config__mdt/fields/resize_column_disabled__c.field-meta.xml
<CustomField>
    <fullName>resize_column_disabled__c</fullName>
    <defaultValue>false</defaultValue>
    <label>resize-column-disabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Grid_Config__mdt/fields/resize_step__c.field-meta.xml
<CustomField>
    <fullName>resize_step__c</fullName>
    <defaultValue>&#39;10px&#39;</defaultValue>
    <label>resize-step</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Grid_Config__mdt/fields/row_number_offset__c.field-meta.xml
<CustomField>
    <fullName>row_number_offset__c</fullName>
    <label>row-number-offset</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Grid_Config__mdt/fields/show_row_number_column__c.field-meta.xml
<CustomField>
    <fullName>show_row_number_column__c</fullName>
    <defaultValue>false</defaultValue>
    <label>show-row-number-column</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Grid_Config__mdt/fields/sorted_by__c.field-meta.xml
<CustomField>
    <fullName>sorted_by__c</fullName>
    <label>sorted-by</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Grid_Config__mdt/fields/sorted_direction__c.field-meta.xml
<CustomField>
    <fullName>sorted_direction__c</fullName>
    <label>sorted-direction</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>asc</fullName>
                <default>true</default>
                <label>asc</label>
            </value>
            <value>
                <fullName>desc</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Grid_Config__mdt/fields/suppress_bottom_bar__c.field-meta.xml
<CustomField>
    <fullName>suppress_bottom_bar__c</fullName>
    <defaultValue>false</defaultValue>
    <label>suppress-bottom-bar</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Grid_Config__mdt/fields/wrap_text_max_lines__c.field-meta.xml
<CustomField>
    <fullName>wrap_text_max_lines__c</fullName>
    <label>wrap-text-max-lines</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/GridConfig.cls
public with sharing class GridConfig {
  Grid_Config__mdt gridConfig = null;
  List<String> criteriaParams = null;

  public GridConfig(String gridConfigName, List<String> criteriaParams) {
    this.gridConfigName = gridConfigName;
    this.criteriaParams = criteriaParams;
    List<Grid_Config__mdt> gridConfigs = [
      SELECT
        Id,
        MasterLabel,
        Label,
        QualifiedApiName,
        Query__c,
        Key_Field__c,
        default_sort_direction__c,
        enable_infinite_loading__c,
        hide_checkbox_column__c,
        hide_table_header__c,
        load_more_offset__c,
        max_column_width__c,
        max_row_selection__c,
        min_column_width__c,
        resize_column_disabled__c,
        resize_step__c,
        row_number_offset__c,
        show_row_number_column__c,
        sorted_by__c,
        sorted_direction__c,
        suppress_bottom_bar__c,
        wrap_text_max_lines__c
      FROM Grid_Config__mdt
      WHERE DeveloperName = :this.gridConfigName
    ];
    if (gridConfigs.size() > 0) {
      gridConfig = gridConfigs[0];
    }
    List<Grid_Column__mdt> columns = [
      SELECT Id, Label, Grid_Config__c, Field_Name__c, Type__c, Sort_Order__c
      FROM Grid_Column__mdt
      WHERE Grid_Config__r.DeveloperName = :this.gridConfigName
      ORDER BY Sort_Order__c
    ];
    for (Grid_Column__mdt column : columns) {
      GridColumn gridColumn = new GridColumn(column);
      this.columns.add(gridColumn);
    }
  }

  public GridConfig(Grid_Config__mdt gridConfig) {
    this.gridConfig = gridConfig;
    if (gridConfig.Grid_Columns__r != null)
      for (Grid_Column__mdt column : gridConfig.Grid_Columns__r) {
        GridColumn gridColumn = new GridColumn(column);
        this.columns.add(gridColumn);
      }
  }

  @AuraEnabled
  public String keyField {
    get {
      return this.gridConfig != null ? this.gridConfig.Key_Field__c : 'Id';
    }
  }
  String query {
    get {
      return this.gridConfig != null ? this.gridConfig.Query__c : null;
    }
  }
  public String gridConfigName;

  @AuraEnabled
  public List<GridColumn> columns = new List<GridColumn>();
  @AuraEnabled
  public List<SObject> data {
    get {
      return Database.query(String.format(this.query, criteriaParams));
    }
  }

  @AuraEnabled
  public String defaultSortDirection {
    get {
      return this.gridConfig != null
        ? this.gridConfig.default_sort_direction__c
        : null;
    }
  }

  @AuraEnabled
  public Boolean enableInfiniteLoading {
    get {
      return this.gridConfig != null
        ? this.gridConfig.enable_infinite_loading__c
        : null;
    }
  }

  @AuraEnabled
  public Boolean hideCheckboxColumn {
    get {
      return this.gridConfig != null
        ? this.gridConfig.hide_checkbox_column__c
        : null;
    }
  }

  @AuraEnabled
  public Boolean hideTableHeader {
    get {
      return this.gridConfig != null
        ? this.gridConfig.hide_table_header__c
        : null;
    }
  }
  @AuraEnabled
  public Decimal loadMoreOffset {
    get {
      return this.gridConfig != null
        ? this.gridConfig.load_more_offset__c
        : null;
    }
  }
  @AuraEnabled
  public String maxColumnWidth {
    get {
      return this.gridConfig != null
        ? this.gridConfig.max_column_width__c
        : null;
    }
  }

  @AuraEnabled
  public Decimal maxRowSelection {
    get {
      return this.gridConfig != null
        ? this.gridConfig.max_row_selection__c
        : null;
    }
  }

  @AuraEnabled
  public String minColumnWidth {
    get {
      return this.gridConfig != null
        ? this.gridConfig.min_column_width__c
        : null;
    }
  }

  @AuraEnabled
  public Decimal wrapTextMaxLines {
    get {
      return this.gridConfig != null
        ? this.gridConfig.wrap_text_max_lines__c
        : null;
    }
  }

  @AuraEnabled
  public Boolean suppressBottomBar {
    get {
      return this.gridConfig != null
        ? this.gridConfig.suppress_bottom_bar__c
        : null;
    }
  }

  @AuraEnabled
  public String sortedDirection {
    get {
      return this.gridConfig != null
        ? this.gridConfig.sorted_direction__c
        : null;
    }
  }
  @AuraEnabled
  public String sortedBy {
    get {
      return this.gridConfig != null ? this.gridConfig.sorted_by__c : null;
    }
  }
  @AuraEnabled
  public Boolean showRowNumberColumn {
    get {
      return this.gridConfig != null
        ? this.gridConfig.show_row_number_column__c
        : null;
    }
  }

  @AuraEnabled
  public Boolean resizeColumnDisabled {
    get {
      return this.gridConfig != null
        ? this.gridConfig.resize_column_disabled__c
        : null;
    }
  }

  @AuraEnabled
  public String resizeStep {
    get {
      return this.gridConfig != null ? this.gridConfig.resize_step__c : null;
    }
  }

  @AuraEnabled
  public Decimal rowNumberOffset {
    get {
      return this.gridConfig != null
        ? this.gridConfig.row_number_offset__c
        : null;
    }
  }
}