force-app/main/default/objects/Grid_Column__mdt/Grid_Column__mdt.object-meta.xml
<CustomObject>
    <label>Grid Column</label>
    <pluralLabel>Grid Columns</pluralLabel>
</CustomObject>

force-app/main/default/objects/Grid_Column__mdt/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>action</fullName>
            </value>
            <value>
                <fullName>boolean</fullName>
            </value>
            <value>
                <fullName>button</fullName>
            </value>
            <value>
                <fullName>button-icon</fullName>
            </value>
            <value>
                <fullName>currency</fullName>
            </value>
            <value>
                <fullName>date</fullName>
            </value>
            <value>
                <fullName>date-local</fullName>
            </value>
            <value>
                <fullName>location</fullName>
            </value>
            <value>
                <fullName>number</fullName>
            </value>
            <value>
                <fullName>percent</fullName>
            </value>
            <value>
                <fullName>phone</fullName>
            </value>
            <value>
                <fullName>text</fullName>
            </value>
            <value>
                <fullName>url</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/GridColumn.cls
public with sharing class GridColumn {
    Grid_Column__mdt column = null;
    public GridColumn(Grid_Column__mdt column) {
        this.column = column;
    }
    @AuraEnabled
    public String label{
        get{
            return this.column != null ? this.column.Label:null;
        }
    }
    @AuraEnabled
    public String fieldName{
        get{
            return this.column != null ? this.column.Field_Name__c:null;
        }
    }
    @AuraEnabled
    public String type{
        get{
            return this.column != null ? this.column.Type__c:null;
        }
    }
}